language: java
jdk:
- oraclejdk8
sudo: required

script: gradle check executeFeatures -DapiToken=1a77ed61bf49f50a95282757b849b099
branches:
only: develop

notifications:
  email: true
  recipients:
  - carlos.gonzales@jalasoft.com
  - AT01@fundacion-jala.org

