language: java
jdk:
- oraclejdk8
sudo: required

script: gradle feature
branches:
only: develop

notifications:
  email: true
  recipients:
  - carlos.gonzales@jalasoft.com
  - AT01@fundacion-jala.org

